apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: vcluster-as-a-service
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - name: dev-thomas
  template:
    metadata:
      name: "{{.name}}-vcaas"
    spec:
      project: default
      source:
        chart: vcluster
        repoURL: https://charts.loft.sh
        targetRevision: 0.20.0-beta.11
        helm:
          releaseName: vcluster
      destination:
        server: "https://kubernetes.default.svc"
        namespace: "{{.name}}"
