//go:build go1.22

// Package v2 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v2

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for ModelsErrorAlreadyExistsType.
const (
	AlreadyExists ModelsErrorAlreadyExistsType = "AlreadyExists"
)

// Defines values for ModelsErrorGenericType.
const (
	Generic ModelsErrorGenericType = "Generic"
)

// Defines values for ModelsErrorNotFoundType.
const (
	NotFound ModelsErrorNotFoundType = "NotFound"
)

// Defines values for ModelsErrorUnauthorizedType.
const (
	Unauthorized ModelsErrorUnauthorizedType = "Unauthorized"
)

// Defines values for ModelsVClusterVersion.
const (
	Local      ModelsVClusterVersion = "Local"
	N0196      ModelsVClusterVersion = "0.19.6"
	N0200Beta9 ModelsVClusterVersion = "0.20.0-beta.9"
	Stable     ModelsVClusterVersion = "Stable"
)

// ModelsErrorAlreadyExists defines model for Models.ErrorAlreadyExists.
type ModelsErrorAlreadyExists struct {
	Detail   string                       `json:"detail"`
	Instance string                       `json:"instance"`
	Title    string                       `json:"title"`
	Type     ModelsErrorAlreadyExistsType `json:"type"`
}

// ModelsErrorAlreadyExistsType defines model for ModelsErrorAlreadyExists.Type.
type ModelsErrorAlreadyExistsType string

// ModelsErrorGeneric defines model for Models.ErrorGeneric.
type ModelsErrorGeneric struct {
	Detail   string                 `json:"detail"`
	Instance string                 `json:"instance"`
	Title    string                 `json:"title"`
	Type     ModelsErrorGenericType `json:"type"`
}

// ModelsErrorGenericType defines model for ModelsErrorGeneric.Type.
type ModelsErrorGenericType string

// ModelsErrorNotFound defines model for Models.ErrorNotFound.
type ModelsErrorNotFound struct {
	Detail   string                  `json:"detail"`
	Instance string                  `json:"instance"`
	Title    string                  `json:"title"`
	Type     ModelsErrorNotFoundType `json:"type"`
}

// ModelsErrorNotFoundType defines model for ModelsErrorNotFound.Type.
type ModelsErrorNotFoundType string

// ModelsErrorUnauthorized defines model for Models.ErrorUnauthorized.
type ModelsErrorUnauthorized struct {
	Detail   string                      `json:"detail"`
	Instance string                      `json:"instance"`
	Title    string                      `json:"title"`
	Type     ModelsErrorUnauthorizedType `json:"type"`
}

// ModelsErrorUnauthorizedType defines model for ModelsErrorUnauthorized.Type.
type ModelsErrorUnauthorizedType string

// ModelsKubernetesNamespace defines model for Models.KubernetesNamespace.
type ModelsKubernetesNamespace struct {
	Name string `json:"name"`
}

// ModelsVCluster defines model for Models.vCluster.
type ModelsVCluster struct {
	Name    string                  `json:"name"`
	Values  *map[string]interface{} `json:"values,omitempty"`
	Version ModelsVClusterVersion   `json:"version"`
}

// ModelsVClusterVersion defines model for Models.vClusterVersion.
type ModelsVClusterVersion string

// ModelsKubeconfigOptionsCertificateAuthorityData defines model for Models.KubeconfigOptions.certificateAuthorityData.
type ModelsKubeconfigOptionsCertificateAuthorityData = []byte

// ModelsKubeconfigOptionsInsecure defines model for Models.KubeconfigOptions.insecure.
type ModelsKubeconfigOptionsInsecure = bool

// ModelsKubeconfigOptionsPublicK8sEndpoint defines model for Models.KubeconfigOptions.publicK8sEndpoint.
type ModelsKubeconfigOptionsPublicK8sEndpoint = string

// NamespaceKubeconfigParams defines parameters for NamespaceKubeconfig.
type NamespaceKubeconfigParams struct {
	Insecure          *ModelsKubeconfigOptionsInsecure          `form:"insecure,omitempty" json:"insecure,omitempty"`
	PublicK8sEndpoint *ModelsKubeconfigOptionsPublicK8sEndpoint `form:"publicK8sEndpoint,omitempty" json:"publicK8sEndpoint,omitempty"`

	// CertificateAuthorityData Base64-encoded certificate data
	CertificateAuthorityData *ModelsKubeconfigOptionsCertificateAuthorityData `form:"certificateAuthorityData,omitempty" json:"certificateAuthorityData,omitempty"`
}

// VClusterServiceDeleteJSONBody defines parameters for VClusterServiceDelete.
type VClusterServiceDeleteJSONBody struct {
	Name *string `json:"name,omitempty"`
}

// VClusterServiceGetParams defines parameters for VClusterServiceGet.
type VClusterServiceGetParams struct {
	Name *string `form:"name,omitempty" json:"name,omitempty"`
}

// VClusterServiceCreateJSONBody defines parameters for VClusterServiceCreate.
type VClusterServiceCreateJSONBody struct {
	Name    *string                 `json:"name,omitempty"`
	Values  *map[string]interface{} `json:"values,omitempty"`
	Version *ModelsVClusterVersion  `json:"version,omitempty"`
}

// VClusterServiceKubeconfigParams defines parameters for VClusterServiceKubeconfig.
type VClusterServiceKubeconfigParams struct {
	Name *string `form:"name,omitempty" json:"name,omitempty"`
}

// VClusterServiceDeleteJSONRequestBody defines body for VClusterServiceDelete for application/json ContentType.
type VClusterServiceDeleteJSONRequestBody VClusterServiceDeleteJSONBody

// VClusterServiceCreateJSONRequestBody defines body for VClusterServiceCreate for application/json ContentType.
type VClusterServiceCreateJSONRequestBody VClusterServiceCreateJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /kubernetes)
	KubernetesList(w http.ResponseWriter, r *http.Request)

	// (DELETE /kubernetes/{namespace})
	NamespaceDelete(w http.ResponseWriter, r *http.Request, namespace string)

	// (GET /kubernetes/{namespace})
	NamespaceGet(w http.ResponseWriter, r *http.Request, namespace string)

	// (POST /kubernetes/{namespace})
	NamespaceCreate(w http.ResponseWriter, r *http.Request, namespace string)

	// (GET /kubernetes/{namespace}/kubeconfig)
	NamespaceKubeconfig(w http.ResponseWriter, r *http.Request, namespace string, params NamespaceKubeconfigParams)

	// (DELETE /kubernetes/{namespace}/vcluster)
	VClusterServiceDelete(w http.ResponseWriter, r *http.Request, namespace string)

	// (GET /kubernetes/{namespace}/vcluster)
	VClusterServiceGet(w http.ResponseWriter, r *http.Request, namespace string, params VClusterServiceGetParams)

	// (PATCH /kubernetes/{namespace}/vcluster)
	VClusterServiceCreate(w http.ResponseWriter, r *http.Request, namespace string)

	// (GET /kubernetes/{namespace}/vcluster/kubeconfig)
	VClusterServiceKubeconfig(w http.ResponseWriter, r *http.Request, namespace string, params VClusterServiceKubeconfigParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// KubernetesList operation middleware
func (siw *ServerInterfaceWrapper) KubernetesList(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.KubernetesList(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// NamespaceDelete operation middleware
func (siw *ServerInterfaceWrapper) NamespaceDelete(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", r.PathValue("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "namespace", Err: err})
		return
	}

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.NamespaceDelete(w, r, namespace)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// NamespaceGet operation middleware
func (siw *ServerInterfaceWrapper) NamespaceGet(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", r.PathValue("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "namespace", Err: err})
		return
	}

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.NamespaceGet(w, r, namespace)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// NamespaceCreate operation middleware
func (siw *ServerInterfaceWrapper) NamespaceCreate(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", r.PathValue("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "namespace", Err: err})
		return
	}

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.NamespaceCreate(w, r, namespace)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// NamespaceKubeconfig operation middleware
func (siw *ServerInterfaceWrapper) NamespaceKubeconfig(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", r.PathValue("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "namespace", Err: err})
		return
	}

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params NamespaceKubeconfigParams

	// ------------- Optional query parameter "insecure" -------------

	err = runtime.BindQueryParameter("form", true, false, "insecure", r.URL.Query(), &params.Insecure)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "insecure", Err: err})
		return
	}

	// ------------- Optional query parameter "publicK8sEndpoint" -------------

	err = runtime.BindQueryParameter("form", true, false, "publicK8sEndpoint", r.URL.Query(), &params.PublicK8sEndpoint)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "publicK8sEndpoint", Err: err})
		return
	}

	// ------------- Optional query parameter "certificateAuthorityData" -------------

	err = runtime.BindQueryParameter("form", true, false, "certificateAuthorityData", r.URL.Query(), &params.CertificateAuthorityData)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "certificateAuthorityData", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.NamespaceKubeconfig(w, r, namespace, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// VClusterServiceDelete operation middleware
func (siw *ServerInterfaceWrapper) VClusterServiceDelete(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", r.PathValue("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "namespace", Err: err})
		return
	}

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.VClusterServiceDelete(w, r, namespace)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// VClusterServiceGet operation middleware
func (siw *ServerInterfaceWrapper) VClusterServiceGet(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", r.PathValue("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "namespace", Err: err})
		return
	}

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params VClusterServiceGetParams

	// ------------- Optional query parameter "name" -------------

	err = runtime.BindQueryParameter("form", true, false, "name", r.URL.Query(), &params.Name)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.VClusterServiceGet(w, r, namespace, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// VClusterServiceCreate operation middleware
func (siw *ServerInterfaceWrapper) VClusterServiceCreate(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", r.PathValue("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "namespace", Err: err})
		return
	}

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.VClusterServiceCreate(w, r, namespace)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// VClusterServiceKubeconfig operation middleware
func (siw *ServerInterfaceWrapper) VClusterServiceKubeconfig(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", r.PathValue("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "namespace", Err: err})
		return
	}

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params VClusterServiceKubeconfigParams

	// ------------- Optional query parameter "name" -------------

	err = runtime.BindQueryParameter("form", true, false, "name", r.URL.Query(), &params.Name)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.VClusterServiceKubeconfig(w, r, namespace, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       *http.ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m *http.ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m *http.ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/kubernetes", wrapper.KubernetesList)
	m.HandleFunc("DELETE "+options.BaseURL+"/kubernetes/{namespace}", wrapper.NamespaceDelete)
	m.HandleFunc("GET "+options.BaseURL+"/kubernetes/{namespace}", wrapper.NamespaceGet)
	m.HandleFunc("POST "+options.BaseURL+"/kubernetes/{namespace}", wrapper.NamespaceCreate)
	m.HandleFunc("GET "+options.BaseURL+"/kubernetes/{namespace}/kubeconfig", wrapper.NamespaceKubeconfig)
	m.HandleFunc("DELETE "+options.BaseURL+"/kubernetes/{namespace}/vcluster", wrapper.VClusterServiceDelete)
	m.HandleFunc("GET "+options.BaseURL+"/kubernetes/{namespace}/vcluster", wrapper.VClusterServiceGet)
	m.HandleFunc("PATCH "+options.BaseURL+"/kubernetes/{namespace}/vcluster", wrapper.VClusterServiceCreate)
	m.HandleFunc("GET "+options.BaseURL+"/kubernetes/{namespace}/vcluster/kubeconfig", wrapper.VClusterServiceKubeconfig)

	return m
}

type KubernetesListRequestObject struct {
}

type KubernetesListResponseObject interface {
	VisitKubernetesListResponse(w http.ResponseWriter) error
}

type KubernetesList200JSONResponse []ModelsKubernetesNamespace

func (response KubernetesList200JSONResponse) VisitKubernetesListResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type KubernetesList400JSONResponse ModelsErrorGeneric

func (response KubernetesList400JSONResponse) VisitKubernetesListResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type KubernetesList401JSONResponse ModelsErrorUnauthorized

func (response KubernetesList401JSONResponse) VisitKubernetesListResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type NamespaceDeleteRequestObject struct {
	Namespace string `json:"namespace"`
}

type NamespaceDeleteResponseObject interface {
	VisitNamespaceDeleteResponse(w http.ResponseWriter) error
}

type NamespaceDelete200JSONResponse bool

func (response NamespaceDelete200JSONResponse) VisitNamespaceDeleteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type NamespaceDelete400JSONResponse ModelsErrorGeneric

func (response NamespaceDelete400JSONResponse) VisitNamespaceDeleteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type NamespaceDelete401JSONResponse ModelsErrorUnauthorized

func (response NamespaceDelete401JSONResponse) VisitNamespaceDeleteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type NamespaceDelete404JSONResponse ModelsErrorNotFound

func (response NamespaceDelete404JSONResponse) VisitNamespaceDeleteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type NamespaceGetRequestObject struct {
	Namespace string `json:"namespace"`
}

type NamespaceGetResponseObject interface {
	VisitNamespaceGetResponse(w http.ResponseWriter) error
}

type NamespaceGet200JSONResponse ModelsKubernetesNamespace

func (response NamespaceGet200JSONResponse) VisitNamespaceGetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type NamespaceGet400JSONResponse ModelsErrorGeneric

func (response NamespaceGet400JSONResponse) VisitNamespaceGetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type NamespaceGet401JSONResponse ModelsErrorUnauthorized

func (response NamespaceGet401JSONResponse) VisitNamespaceGetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type NamespaceGet404JSONResponse ModelsErrorNotFound

func (response NamespaceGet404JSONResponse) VisitNamespaceGetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type NamespaceCreateRequestObject struct {
	Namespace string `json:"namespace"`
}

type NamespaceCreateResponseObject interface {
	VisitNamespaceCreateResponse(w http.ResponseWriter) error
}

type NamespaceCreate200JSONResponse ModelsKubernetesNamespace

func (response NamespaceCreate200JSONResponse) VisitNamespaceCreateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type NamespaceCreate400JSONResponse ModelsErrorGeneric

func (response NamespaceCreate400JSONResponse) VisitNamespaceCreateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type NamespaceCreate401JSONResponse ModelsErrorUnauthorized

func (response NamespaceCreate401JSONResponse) VisitNamespaceCreateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type NamespaceCreate409JSONResponse ModelsErrorAlreadyExists

func (response NamespaceCreate409JSONResponse) VisitNamespaceCreateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type NamespaceKubeconfigRequestObject struct {
	Namespace string `json:"namespace"`
	Params    NamespaceKubeconfigParams
}

type NamespaceKubeconfigResponseObject interface {
	VisitNamespaceKubeconfigResponse(w http.ResponseWriter) error
}

type NamespaceKubeconfig200TextyamlResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response NamespaceKubeconfig200TextyamlResponse) VisitNamespaceKubeconfigResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/yaml")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type NamespaceKubeconfig401JSONResponse ModelsErrorUnauthorized

func (response NamespaceKubeconfig401JSONResponse) VisitNamespaceKubeconfigResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type NamespaceKubeconfig404JSONResponse ModelsErrorNotFound

func (response NamespaceKubeconfig404JSONResponse) VisitNamespaceKubeconfigResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type VClusterServiceDeleteRequestObject struct {
	Namespace string `json:"namespace"`
	Body      *VClusterServiceDeleteJSONRequestBody
}

type VClusterServiceDeleteResponseObject interface {
	VisitVClusterServiceDeleteResponse(w http.ResponseWriter) error
}

type VClusterServiceDelete200JSONResponse bool

func (response VClusterServiceDelete200JSONResponse) VisitVClusterServiceDeleteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type VClusterServiceDelete401JSONResponse ModelsErrorUnauthorized

func (response VClusterServiceDelete401JSONResponse) VisitVClusterServiceDeleteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type VClusterServiceDelete404JSONResponse ModelsErrorNotFound

func (response VClusterServiceDelete404JSONResponse) VisitVClusterServiceDeleteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type VClusterServiceGetRequestObject struct {
	Namespace string `json:"namespace"`
	Params    VClusterServiceGetParams
}

type VClusterServiceGetResponseObject interface {
	VisitVClusterServiceGetResponse(w http.ResponseWriter) error
}

type VClusterServiceGet200JSONResponse ModelsVCluster

func (response VClusterServiceGet200JSONResponse) VisitVClusterServiceGetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type VClusterServiceGet401JSONResponse ModelsErrorUnauthorized

func (response VClusterServiceGet401JSONResponse) VisitVClusterServiceGetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type VClusterServiceGet404JSONResponse ModelsErrorNotFound

func (response VClusterServiceGet404JSONResponse) VisitVClusterServiceGetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type VClusterServiceCreateRequestObject struct {
	Namespace string `json:"namespace"`
	Body      *VClusterServiceCreateJSONRequestBody
}

type VClusterServiceCreateResponseObject interface {
	VisitVClusterServiceCreateResponse(w http.ResponseWriter) error
}

type VClusterServiceCreate200JSONResponse ModelsVCluster

func (response VClusterServiceCreate200JSONResponse) VisitVClusterServiceCreateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type VClusterServiceCreate401JSONResponse ModelsErrorUnauthorized

func (response VClusterServiceCreate401JSONResponse) VisitVClusterServiceCreateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type VClusterServiceCreate404JSONResponse ModelsErrorNotFound

func (response VClusterServiceCreate404JSONResponse) VisitVClusterServiceCreateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type VClusterServiceKubeconfigRequestObject struct {
	Namespace string `json:"namespace"`
	Params    VClusterServiceKubeconfigParams
}

type VClusterServiceKubeconfigResponseObject interface {
	VisitVClusterServiceKubeconfigResponse(w http.ResponseWriter) error
}

type VClusterServiceKubeconfig200TextyamlResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response VClusterServiceKubeconfig200TextyamlResponse) VisitVClusterServiceKubeconfigResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/yaml")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type VClusterServiceKubeconfig401JSONResponse ModelsErrorUnauthorized

func (response VClusterServiceKubeconfig401JSONResponse) VisitVClusterServiceKubeconfigResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type VClusterServiceKubeconfig404JSONResponse ModelsErrorNotFound

func (response VClusterServiceKubeconfig404JSONResponse) VisitVClusterServiceKubeconfigResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (GET /kubernetes)
	KubernetesList(ctx context.Context, request KubernetesListRequestObject) (KubernetesListResponseObject, error)

	// (DELETE /kubernetes/{namespace})
	NamespaceDelete(ctx context.Context, request NamespaceDeleteRequestObject) (NamespaceDeleteResponseObject, error)

	// (GET /kubernetes/{namespace})
	NamespaceGet(ctx context.Context, request NamespaceGetRequestObject) (NamespaceGetResponseObject, error)

	// (POST /kubernetes/{namespace})
	NamespaceCreate(ctx context.Context, request NamespaceCreateRequestObject) (NamespaceCreateResponseObject, error)

	// (GET /kubernetes/{namespace}/kubeconfig)
	NamespaceKubeconfig(ctx context.Context, request NamespaceKubeconfigRequestObject) (NamespaceKubeconfigResponseObject, error)

	// (DELETE /kubernetes/{namespace}/vcluster)
	VClusterServiceDelete(ctx context.Context, request VClusterServiceDeleteRequestObject) (VClusterServiceDeleteResponseObject, error)

	// (GET /kubernetes/{namespace}/vcluster)
	VClusterServiceGet(ctx context.Context, request VClusterServiceGetRequestObject) (VClusterServiceGetResponseObject, error)

	// (PATCH /kubernetes/{namespace}/vcluster)
	VClusterServiceCreate(ctx context.Context, request VClusterServiceCreateRequestObject) (VClusterServiceCreateResponseObject, error)

	// (GET /kubernetes/{namespace}/vcluster/kubeconfig)
	VClusterServiceKubeconfig(ctx context.Context, request VClusterServiceKubeconfigRequestObject) (VClusterServiceKubeconfigResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// KubernetesList operation middleware
func (sh *strictHandler) KubernetesList(w http.ResponseWriter, r *http.Request) {
	var request KubernetesListRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.KubernetesList(ctx, request.(KubernetesListRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "KubernetesList")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(KubernetesListResponseObject); ok {
		if err := validResponse.VisitKubernetesListResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// NamespaceDelete operation middleware
func (sh *strictHandler) NamespaceDelete(w http.ResponseWriter, r *http.Request, namespace string) {
	var request NamespaceDeleteRequestObject

	request.Namespace = namespace

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.NamespaceDelete(ctx, request.(NamespaceDeleteRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "NamespaceDelete")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(NamespaceDeleteResponseObject); ok {
		if err := validResponse.VisitNamespaceDeleteResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// NamespaceGet operation middleware
func (sh *strictHandler) NamespaceGet(w http.ResponseWriter, r *http.Request, namespace string) {
	var request NamespaceGetRequestObject

	request.Namespace = namespace

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.NamespaceGet(ctx, request.(NamespaceGetRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "NamespaceGet")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(NamespaceGetResponseObject); ok {
		if err := validResponse.VisitNamespaceGetResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// NamespaceCreate operation middleware
func (sh *strictHandler) NamespaceCreate(w http.ResponseWriter, r *http.Request, namespace string) {
	var request NamespaceCreateRequestObject

	request.Namespace = namespace

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.NamespaceCreate(ctx, request.(NamespaceCreateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "NamespaceCreate")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(NamespaceCreateResponseObject); ok {
		if err := validResponse.VisitNamespaceCreateResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// NamespaceKubeconfig operation middleware
func (sh *strictHandler) NamespaceKubeconfig(w http.ResponseWriter, r *http.Request, namespace string, params NamespaceKubeconfigParams) {
	var request NamespaceKubeconfigRequestObject

	request.Namespace = namespace
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.NamespaceKubeconfig(ctx, request.(NamespaceKubeconfigRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "NamespaceKubeconfig")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(NamespaceKubeconfigResponseObject); ok {
		if err := validResponse.VisitNamespaceKubeconfigResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// VClusterServiceDelete operation middleware
func (sh *strictHandler) VClusterServiceDelete(w http.ResponseWriter, r *http.Request, namespace string) {
	var request VClusterServiceDeleteRequestObject

	request.Namespace = namespace

	var body VClusterServiceDeleteJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.VClusterServiceDelete(ctx, request.(VClusterServiceDeleteRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "VClusterServiceDelete")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(VClusterServiceDeleteResponseObject); ok {
		if err := validResponse.VisitVClusterServiceDeleteResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// VClusterServiceGet operation middleware
func (sh *strictHandler) VClusterServiceGet(w http.ResponseWriter, r *http.Request, namespace string, params VClusterServiceGetParams) {
	var request VClusterServiceGetRequestObject

	request.Namespace = namespace
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.VClusterServiceGet(ctx, request.(VClusterServiceGetRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "VClusterServiceGet")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(VClusterServiceGetResponseObject); ok {
		if err := validResponse.VisitVClusterServiceGetResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// VClusterServiceCreate operation middleware
func (sh *strictHandler) VClusterServiceCreate(w http.ResponseWriter, r *http.Request, namespace string) {
	var request VClusterServiceCreateRequestObject

	request.Namespace = namespace

	var body VClusterServiceCreateJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.VClusterServiceCreate(ctx, request.(VClusterServiceCreateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "VClusterServiceCreate")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(VClusterServiceCreateResponseObject); ok {
		if err := validResponse.VisitVClusterServiceCreateResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// VClusterServiceKubeconfig operation middleware
func (sh *strictHandler) VClusterServiceKubeconfig(w http.ResponseWriter, r *http.Request, namespace string, params VClusterServiceKubeconfigParams) {
	var request VClusterServiceKubeconfigRequestObject

	request.Namespace = namespace
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.VClusterServiceKubeconfig(ctx, request.(VClusterServiceKubeconfigRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "VClusterServiceKubeconfig")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(VClusterServiceKubeconfigResponseObject); ok {
		if err := validResponse.VisitVClusterServiceKubeconfigResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+wZW3MaN/evaPR9jxvArpvGvDnOZTJJE0/Tpg+JHw7ag1EqpI10REwZ/ntH0sLumgUc",
	"O+Bkhieblc79fjTjwowLo1GT4/0ZL8DCGAlt/PW7yVG5zms/QGH0UF69K0ga7ToCLcmhFEB45mlkrKTp",
	"MyAIQDk6YWW8yPv8KTh8fPIItTA55qwGyPIAkHEZrn3xaKc84xrGyPt8Lf6MOzHCcSQ0NHYMxPt8MCXk",
	"GadpEWAdWamv+HyeredfaofCWwxo2ugvz+v0SvwDYxSC3kyg8AMlxesn7rnOCyM1raO0erGF5FKk+eKw",
	"bp7n1hp7pixCPn1+LV1pSWuKoEV0ySgEUrWgDPp3BFpg6yFJUmtO4ocZR+3HvP+RNxm4bDOHxS9eWszD",
	"9Xi6wJ8t+KtxU2Ewg88oiFfqjgK/RI1WiocQdUF690K+NfTCeJ0/hJRL2rsX8y8NKcr/xQcRtUF/p+KG",
	"TGE1Erq3MEZXQOK9KXBKDTM+hus3qK9oxPuPTzI+lnrx82gbjxHFBj4m58o7Qvt9iGd8AsoneMhzGXIg",
	"qIs63nkLLxO0LlaJGf+/xSHv8/91q3LULTNd9wbLH0qoVpErpLcQ/kNFf+EJ7wkG0apvjIBg1F7n6LTz",
	"OP5z3Ov0Hg2QoHPa7iSxZkiavg+MJ208RbBoQw0Lv6JEsYbEz1XNGhEVKb1LPTSrVfTs4hVDDQMl9RWb",
	"Gs/IsMKaiQz8s6AzT8gEFCAkTZnUDFjlakwkeT/pT/qPF+fs9OTX3yIQkEzSlqHCz0tMFwoolFf2Hu1E",
	"irpe+3xyHHRpCtRQSN7nv3R6nR7PeAE0ikJ3/1mSDj+vkFYleiMdMVCqzqZehISLMpqvmkc6FgLQq5z3",
	"eXU7IODBA1xhtEuUjnu98EcYTZhKLhSFCm2ENLr72SVbV+VVEo7dLd2vLXIrpwZrYZos2JTzzxGy4KXo",
	"iI3AMeeFQMwx7wTok29k+BZ8NorjGoYc2glaJoxXOdOGmNc52pC9ckY1hnOPwdOknoCSOXNTTXBdMn60",
	"E8YbmbiF+zMh0DkmHfO1m51wdZ7VHa87W3rTPHmfQsJVP3wWvzfDZQm51g2XLpDAo/NXjfPHstULAVF1",
	"ekusvJ63yHrc1PFd3tPFV5rWg4c+kIcGlk52wtKyU9uiTNBBk0PZ1CHmzKIz3grsJAytCfslEkutjmMw",
	"MJ7uHDMvkX7ggLlrKTgE1iGwtgVWYVxLZJ1bhLUlaH0YJbDVSFplMyBjZhgi09YClQwbIBMRTb5YxBxC",
	"8BCCdwvB052w1FwrbTGxMHqopCDHvkoaRWUKby1qYo5CjJlh/JgssKVrjJ/TVm/tFBOKYorbdDHYC5KS",
	"msHWCbPX31IpZpG81U2oKYwVG0qFke9PukRBJnJbIVmfDCpkOyytWbvZKnLd7QvX+yBZ3ZXeB9vaHfMt",
	"8hfhNXWD1ZpOXW2kpYa45W1Z4H5bhjrU2jvV2g1hPRHV6quaCptx9aHcEJXrj/1MeVGQpyaffpN+b7W9",
	"W91V3diNNZdpgd35gw+eB9e/3/y20aV3O4Rl7Y9d5Yq2gtvipntoJJeL8IOD7nEOAhKjDYOQxq9sYRhm",
	"LPNFHg80w9AHSn3FjF4djW64+LoB6WfN2vd/ZQGl3g2jDu7y3nIZTD8Er0KHUz6U7KWUHML4J22xvscI",
	"tbDsjiaoGzljX3PUfqrjYUz50WOo9mocfaz+XvzxMpg4IWxb7Z1dvGKL5J5xb1X5kNzvdpURoEbGUf9J",
	"70mvOyuvzXmoIVaG1B1dplYbqtQ+OeLZRlKLx/J4cXLML+fz+eX8vwAAAP//SxplP0smAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
