//go:build go1.22

// Package v2 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v2

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for ModelsErrorAlreadyExistsType.
const (
	AlreadyExists ModelsErrorAlreadyExistsType = "AlreadyExists"
)

// Defines values for ModelsErrorGenericType.
const (
	Generic ModelsErrorGenericType = "Generic"
)

// Defines values for ModelsErrorNotFoundType.
const (
	NotFound ModelsErrorNotFoundType = "NotFound"
)

// Defines values for ModelsErrorUnauthorizedType.
const (
	Unauthorized ModelsErrorUnauthorizedType = "Unauthorized"
)

// Defines values for ModelsVClusterVersion.
const (
	N0195      ModelsVClusterVersion = "0.19.5"
	N0200Beta9 ModelsVClusterVersion = "0.20.0-beta.9"
)

// ModelsErrorAlreadyExists defines model for Models.ErrorAlreadyExists.
type ModelsErrorAlreadyExists struct {
	Detail   string                       `json:"detail"`
	Instance string                       `json:"instance"`
	Title    string                       `json:"title"`
	Type     ModelsErrorAlreadyExistsType `json:"type"`
}

// ModelsErrorAlreadyExistsType defines model for ModelsErrorAlreadyExists.Type.
type ModelsErrorAlreadyExistsType string

// ModelsErrorGeneric defines model for Models.ErrorGeneric.
type ModelsErrorGeneric struct {
	Detail   string                 `json:"detail"`
	Instance string                 `json:"instance"`
	Title    string                 `json:"title"`
	Type     ModelsErrorGenericType `json:"type"`
}

// ModelsErrorGenericType defines model for ModelsErrorGeneric.Type.
type ModelsErrorGenericType string

// ModelsErrorNotFound defines model for Models.ErrorNotFound.
type ModelsErrorNotFound struct {
	Detail   string                  `json:"detail"`
	Instance string                  `json:"instance"`
	Title    string                  `json:"title"`
	Type     ModelsErrorNotFoundType `json:"type"`
}

// ModelsErrorNotFoundType defines model for ModelsErrorNotFound.Type.
type ModelsErrorNotFoundType string

// ModelsErrorUnauthorized defines model for Models.ErrorUnauthorized.
type ModelsErrorUnauthorized struct {
	Detail   string                      `json:"detail"`
	Instance string                      `json:"instance"`
	Title    string                      `json:"title"`
	Type     ModelsErrorUnauthorizedType `json:"type"`
}

// ModelsErrorUnauthorizedType defines model for ModelsErrorUnauthorized.Type.
type ModelsErrorUnauthorizedType string

// ModelsKubernetesNamespace defines model for Models.KubernetesNamespace.
type ModelsKubernetesNamespace struct {
	Name string `json:"name"`
}

// ModelsVCluster defines model for Models.vCluster.
type ModelsVCluster struct {
	Name    string                `json:"name"`
	Version ModelsVClusterVersion `json:"version"`
}

// ModelsVClusterVersion defines model for ModelsVCluster.Version.
type ModelsVClusterVersion string

// ModelsKubeconfigOptionsCertificateAuthorityData defines model for Models.KubeconfigOptions.certificateAuthorityData.
type ModelsKubeconfigOptionsCertificateAuthorityData = []byte

// ModelsKubeconfigOptionsInsecure defines model for Models.KubeconfigOptions.insecure.
type ModelsKubeconfigOptionsInsecure = bool

// ModelsKubeconfigOptionsPublicK8sEndpoint defines model for Models.KubeconfigOptions.publicK8sEndpoint.
type ModelsKubeconfigOptionsPublicK8sEndpoint = string

// NamespaceKubeconfigParams defines parameters for NamespaceKubeconfig.
type NamespaceKubeconfigParams struct {
	Insecure          *ModelsKubeconfigOptionsInsecure          `form:"insecure,omitempty" json:"insecure,omitempty"`
	PublicK8sEndpoint *ModelsKubeconfigOptionsPublicK8sEndpoint `form:"publicK8sEndpoint,omitempty" json:"publicK8sEndpoint,omitempty"`

	// CertificateAuthorityData Base64-encoded certificate data
	CertificateAuthorityData *ModelsKubeconfigOptionsCertificateAuthorityData `form:"certificateAuthorityData,omitempty" json:"certificateAuthorityData,omitempty"`
}

// VClusterServiceKubeconfigParams defines parameters for VClusterServiceKubeconfig.
type VClusterServiceKubeconfigParams struct {
	Insecure          *ModelsKubeconfigOptionsInsecure          `form:"insecure,omitempty" json:"insecure,omitempty"`
	PublicK8sEndpoint *ModelsKubeconfigOptionsPublicK8sEndpoint `form:"publicK8sEndpoint,omitempty" json:"publicK8sEndpoint,omitempty"`

	// CertificateAuthorityData Base64-encoded certificate data
	CertificateAuthorityData *ModelsKubeconfigOptionsCertificateAuthorityData `form:"certificateAuthorityData,omitempty" json:"certificateAuthorityData,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /kubernetes)
	KubernetesList(w http.ResponseWriter, r *http.Request)

	// (DELETE /kubernetes/{namespace})
	NamespaceDelete(w http.ResponseWriter, r *http.Request, namespace string)

	// (GET /kubernetes/{namespace})
	NamespaceGet(w http.ResponseWriter, r *http.Request, namespace string)

	// (POST /kubernetes/{namespace})
	NamespaceCreate(w http.ResponseWriter, r *http.Request, namespace string)

	// (GET /kubernetes/{namespace}/kubeconfig)
	NamespaceKubeconfig(w http.ResponseWriter, r *http.Request, namespace string, params NamespaceKubeconfigParams)

	// (DELETE /kubernetes/{namespace}/vcluster)
	VClusterServiceDelete(w http.ResponseWriter, r *http.Request, namespace string)

	// (GET /kubernetes/{namespace}/vcluster)
	VClusterServiceGet(w http.ResponseWriter, r *http.Request, namespace string)

	// (POST /kubernetes/{namespace}/vcluster)
	VClusterServiceCreate(w http.ResponseWriter, r *http.Request, namespace string)

	// (GET /kubernetes/{namespace}/vcluster/kubeconfig)
	VClusterServiceKubeconfig(w http.ResponseWriter, r *http.Request, namespace string, params VClusterServiceKubeconfigParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// KubernetesList operation middleware
func (siw *ServerInterfaceWrapper) KubernetesList(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.KubernetesList(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// NamespaceDelete operation middleware
func (siw *ServerInterfaceWrapper) NamespaceDelete(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", r.PathValue("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "namespace", Err: err})
		return
	}

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.NamespaceDelete(w, r, namespace)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// NamespaceGet operation middleware
func (siw *ServerInterfaceWrapper) NamespaceGet(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", r.PathValue("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "namespace", Err: err})
		return
	}

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.NamespaceGet(w, r, namespace)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// NamespaceCreate operation middleware
func (siw *ServerInterfaceWrapper) NamespaceCreate(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", r.PathValue("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "namespace", Err: err})
		return
	}

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.NamespaceCreate(w, r, namespace)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// NamespaceKubeconfig operation middleware
func (siw *ServerInterfaceWrapper) NamespaceKubeconfig(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", r.PathValue("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "namespace", Err: err})
		return
	}

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params NamespaceKubeconfigParams

	// ------------- Optional query parameter "insecure" -------------

	err = runtime.BindQueryParameter("form", true, false, "insecure", r.URL.Query(), &params.Insecure)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "insecure", Err: err})
		return
	}

	// ------------- Optional query parameter "publicK8sEndpoint" -------------

	err = runtime.BindQueryParameter("form", true, false, "publicK8sEndpoint", r.URL.Query(), &params.PublicK8sEndpoint)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "publicK8sEndpoint", Err: err})
		return
	}

	// ------------- Optional query parameter "certificateAuthorityData" -------------

	err = runtime.BindQueryParameter("form", true, false, "certificateAuthorityData", r.URL.Query(), &params.CertificateAuthorityData)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "certificateAuthorityData", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.NamespaceKubeconfig(w, r, namespace, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// VClusterServiceDelete operation middleware
func (siw *ServerInterfaceWrapper) VClusterServiceDelete(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", r.PathValue("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "namespace", Err: err})
		return
	}

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.VClusterServiceDelete(w, r, namespace)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// VClusterServiceGet operation middleware
func (siw *ServerInterfaceWrapper) VClusterServiceGet(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", r.PathValue("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "namespace", Err: err})
		return
	}

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.VClusterServiceGet(w, r, namespace)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// VClusterServiceCreate operation middleware
func (siw *ServerInterfaceWrapper) VClusterServiceCreate(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", r.PathValue("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "namespace", Err: err})
		return
	}

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.VClusterServiceCreate(w, r, namespace)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// VClusterServiceKubeconfig operation middleware
func (siw *ServerInterfaceWrapper) VClusterServiceKubeconfig(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", r.PathValue("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "namespace", Err: err})
		return
	}

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params VClusterServiceKubeconfigParams

	// ------------- Optional query parameter "insecure" -------------

	err = runtime.BindQueryParameter("form", true, false, "insecure", r.URL.Query(), &params.Insecure)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "insecure", Err: err})
		return
	}

	// ------------- Optional query parameter "publicK8sEndpoint" -------------

	err = runtime.BindQueryParameter("form", true, false, "publicK8sEndpoint", r.URL.Query(), &params.PublicK8sEndpoint)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "publicK8sEndpoint", Err: err})
		return
	}

	// ------------- Optional query parameter "certificateAuthorityData" -------------

	err = runtime.BindQueryParameter("form", true, false, "certificateAuthorityData", r.URL.Query(), &params.CertificateAuthorityData)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "certificateAuthorityData", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.VClusterServiceKubeconfig(w, r, namespace, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       *http.ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m *http.ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m *http.ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/kubernetes", wrapper.KubernetesList)
	m.HandleFunc("DELETE "+options.BaseURL+"/kubernetes/{namespace}", wrapper.NamespaceDelete)
	m.HandleFunc("GET "+options.BaseURL+"/kubernetes/{namespace}", wrapper.NamespaceGet)
	m.HandleFunc("POST "+options.BaseURL+"/kubernetes/{namespace}", wrapper.NamespaceCreate)
	m.HandleFunc("GET "+options.BaseURL+"/kubernetes/{namespace}/kubeconfig", wrapper.NamespaceKubeconfig)
	m.HandleFunc("DELETE "+options.BaseURL+"/kubernetes/{namespace}/vcluster", wrapper.VClusterServiceDelete)
	m.HandleFunc("GET "+options.BaseURL+"/kubernetes/{namespace}/vcluster", wrapper.VClusterServiceGet)
	m.HandleFunc("POST "+options.BaseURL+"/kubernetes/{namespace}/vcluster", wrapper.VClusterServiceCreate)
	m.HandleFunc("GET "+options.BaseURL+"/kubernetes/{namespace}/vcluster/kubeconfig", wrapper.VClusterServiceKubeconfig)

	return m
}

type KubernetesListRequestObject struct {
}

type KubernetesListResponseObject interface {
	VisitKubernetesListResponse(w http.ResponseWriter) error
}

type KubernetesList200JSONResponse []ModelsKubernetesNamespace

func (response KubernetesList200JSONResponse) VisitKubernetesListResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type KubernetesList400JSONResponse ModelsErrorGeneric

func (response KubernetesList400JSONResponse) VisitKubernetesListResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type KubernetesList401JSONResponse ModelsErrorUnauthorized

func (response KubernetesList401JSONResponse) VisitKubernetesListResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type NamespaceDeleteRequestObject struct {
	Namespace string `json:"namespace"`
}

type NamespaceDeleteResponseObject interface {
	VisitNamespaceDeleteResponse(w http.ResponseWriter) error
}

type NamespaceDelete200JSONResponse bool

func (response NamespaceDelete200JSONResponse) VisitNamespaceDeleteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type NamespaceDelete400JSONResponse ModelsErrorGeneric

func (response NamespaceDelete400JSONResponse) VisitNamespaceDeleteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type NamespaceDelete401JSONResponse ModelsErrorUnauthorized

func (response NamespaceDelete401JSONResponse) VisitNamespaceDeleteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type NamespaceDelete404JSONResponse ModelsErrorNotFound

func (response NamespaceDelete404JSONResponse) VisitNamespaceDeleteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type NamespaceGetRequestObject struct {
	Namespace string `json:"namespace"`
}

type NamespaceGetResponseObject interface {
	VisitNamespaceGetResponse(w http.ResponseWriter) error
}

type NamespaceGet200JSONResponse ModelsKubernetesNamespace

func (response NamespaceGet200JSONResponse) VisitNamespaceGetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type NamespaceGet400JSONResponse ModelsErrorGeneric

func (response NamespaceGet400JSONResponse) VisitNamespaceGetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type NamespaceGet401JSONResponse ModelsErrorUnauthorized

func (response NamespaceGet401JSONResponse) VisitNamespaceGetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type NamespaceGet404JSONResponse ModelsErrorNotFound

func (response NamespaceGet404JSONResponse) VisitNamespaceGetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type NamespaceCreateRequestObject struct {
	Namespace string `json:"namespace"`
}

type NamespaceCreateResponseObject interface {
	VisitNamespaceCreateResponse(w http.ResponseWriter) error
}

type NamespaceCreate200JSONResponse ModelsKubernetesNamespace

func (response NamespaceCreate200JSONResponse) VisitNamespaceCreateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type NamespaceCreate400JSONResponse ModelsErrorGeneric

func (response NamespaceCreate400JSONResponse) VisitNamespaceCreateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type NamespaceCreate401JSONResponse ModelsErrorUnauthorized

func (response NamespaceCreate401JSONResponse) VisitNamespaceCreateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type NamespaceCreate409JSONResponse ModelsErrorAlreadyExists

func (response NamespaceCreate409JSONResponse) VisitNamespaceCreateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type NamespaceKubeconfigRequestObject struct {
	Namespace string `json:"namespace"`
	Params    NamespaceKubeconfigParams
}

type NamespaceKubeconfigResponseObject interface {
	VisitNamespaceKubeconfigResponse(w http.ResponseWriter) error
}

type NamespaceKubeconfig200TextyamlResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response NamespaceKubeconfig200TextyamlResponse) VisitNamespaceKubeconfigResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/yaml")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type NamespaceKubeconfig401JSONResponse ModelsErrorUnauthorized

func (response NamespaceKubeconfig401JSONResponse) VisitNamespaceKubeconfigResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type NamespaceKubeconfig404JSONResponse ModelsErrorNotFound

func (response NamespaceKubeconfig404JSONResponse) VisitNamespaceKubeconfigResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type VClusterServiceDeleteRequestObject struct {
	Namespace string `json:"namespace"`
}

type VClusterServiceDeleteResponseObject interface {
	VisitVClusterServiceDeleteResponse(w http.ResponseWriter) error
}

type VClusterServiceDelete200JSONResponse bool

func (response VClusterServiceDelete200JSONResponse) VisitVClusterServiceDeleteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type VClusterServiceDelete401JSONResponse ModelsErrorUnauthorized

func (response VClusterServiceDelete401JSONResponse) VisitVClusterServiceDeleteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type VClusterServiceDelete404JSONResponse ModelsErrorNotFound

func (response VClusterServiceDelete404JSONResponse) VisitVClusterServiceDeleteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type VClusterServiceGetRequestObject struct {
	Namespace string `json:"namespace"`
}

type VClusterServiceGetResponseObject interface {
	VisitVClusterServiceGetResponse(w http.ResponseWriter) error
}

type VClusterServiceGet200JSONResponse ModelsVCluster

func (response VClusterServiceGet200JSONResponse) VisitVClusterServiceGetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type VClusterServiceGet401JSONResponse ModelsErrorUnauthorized

func (response VClusterServiceGet401JSONResponse) VisitVClusterServiceGetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type VClusterServiceGet404JSONResponse ModelsErrorNotFound

func (response VClusterServiceGet404JSONResponse) VisitVClusterServiceGetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type VClusterServiceCreateRequestObject struct {
	Namespace string `json:"namespace"`
}

type VClusterServiceCreateResponseObject interface {
	VisitVClusterServiceCreateResponse(w http.ResponseWriter) error
}

type VClusterServiceCreate200JSONResponse ModelsVCluster

func (response VClusterServiceCreate200JSONResponse) VisitVClusterServiceCreateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type VClusterServiceCreate401JSONResponse ModelsErrorUnauthorized

func (response VClusterServiceCreate401JSONResponse) VisitVClusterServiceCreateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type VClusterServiceCreate404JSONResponse ModelsErrorNotFound

func (response VClusterServiceCreate404JSONResponse) VisitVClusterServiceCreateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type VClusterServiceKubeconfigRequestObject struct {
	Namespace string `json:"namespace"`
	Params    VClusterServiceKubeconfigParams
}

type VClusterServiceKubeconfigResponseObject interface {
	VisitVClusterServiceKubeconfigResponse(w http.ResponseWriter) error
}

type VClusterServiceKubeconfig200TextyamlResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response VClusterServiceKubeconfig200TextyamlResponse) VisitVClusterServiceKubeconfigResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/yaml")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type VClusterServiceKubeconfig401JSONResponse ModelsErrorUnauthorized

func (response VClusterServiceKubeconfig401JSONResponse) VisitVClusterServiceKubeconfigResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type VClusterServiceKubeconfig404JSONResponse ModelsErrorNotFound

func (response VClusterServiceKubeconfig404JSONResponse) VisitVClusterServiceKubeconfigResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (GET /kubernetes)
	KubernetesList(ctx context.Context, request KubernetesListRequestObject) (KubernetesListResponseObject, error)

	// (DELETE /kubernetes/{namespace})
	NamespaceDelete(ctx context.Context, request NamespaceDeleteRequestObject) (NamespaceDeleteResponseObject, error)

	// (GET /kubernetes/{namespace})
	NamespaceGet(ctx context.Context, request NamespaceGetRequestObject) (NamespaceGetResponseObject, error)

	// (POST /kubernetes/{namespace})
	NamespaceCreate(ctx context.Context, request NamespaceCreateRequestObject) (NamespaceCreateResponseObject, error)

	// (GET /kubernetes/{namespace}/kubeconfig)
	NamespaceKubeconfig(ctx context.Context, request NamespaceKubeconfigRequestObject) (NamespaceKubeconfigResponseObject, error)

	// (DELETE /kubernetes/{namespace}/vcluster)
	VClusterServiceDelete(ctx context.Context, request VClusterServiceDeleteRequestObject) (VClusterServiceDeleteResponseObject, error)

	// (GET /kubernetes/{namespace}/vcluster)
	VClusterServiceGet(ctx context.Context, request VClusterServiceGetRequestObject) (VClusterServiceGetResponseObject, error)

	// (POST /kubernetes/{namespace}/vcluster)
	VClusterServiceCreate(ctx context.Context, request VClusterServiceCreateRequestObject) (VClusterServiceCreateResponseObject, error)

	// (GET /kubernetes/{namespace}/vcluster/kubeconfig)
	VClusterServiceKubeconfig(ctx context.Context, request VClusterServiceKubeconfigRequestObject) (VClusterServiceKubeconfigResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// KubernetesList operation middleware
func (sh *strictHandler) KubernetesList(w http.ResponseWriter, r *http.Request) {
	var request KubernetesListRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.KubernetesList(ctx, request.(KubernetesListRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "KubernetesList")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(KubernetesListResponseObject); ok {
		if err := validResponse.VisitKubernetesListResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// NamespaceDelete operation middleware
func (sh *strictHandler) NamespaceDelete(w http.ResponseWriter, r *http.Request, namespace string) {
	var request NamespaceDeleteRequestObject

	request.Namespace = namespace

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.NamespaceDelete(ctx, request.(NamespaceDeleteRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "NamespaceDelete")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(NamespaceDeleteResponseObject); ok {
		if err := validResponse.VisitNamespaceDeleteResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// NamespaceGet operation middleware
func (sh *strictHandler) NamespaceGet(w http.ResponseWriter, r *http.Request, namespace string) {
	var request NamespaceGetRequestObject

	request.Namespace = namespace

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.NamespaceGet(ctx, request.(NamespaceGetRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "NamespaceGet")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(NamespaceGetResponseObject); ok {
		if err := validResponse.VisitNamespaceGetResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// NamespaceCreate operation middleware
func (sh *strictHandler) NamespaceCreate(w http.ResponseWriter, r *http.Request, namespace string) {
	var request NamespaceCreateRequestObject

	request.Namespace = namespace

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.NamespaceCreate(ctx, request.(NamespaceCreateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "NamespaceCreate")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(NamespaceCreateResponseObject); ok {
		if err := validResponse.VisitNamespaceCreateResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// NamespaceKubeconfig operation middleware
func (sh *strictHandler) NamespaceKubeconfig(w http.ResponseWriter, r *http.Request, namespace string, params NamespaceKubeconfigParams) {
	var request NamespaceKubeconfigRequestObject

	request.Namespace = namespace
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.NamespaceKubeconfig(ctx, request.(NamespaceKubeconfigRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "NamespaceKubeconfig")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(NamespaceKubeconfigResponseObject); ok {
		if err := validResponse.VisitNamespaceKubeconfigResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// VClusterServiceDelete operation middleware
func (sh *strictHandler) VClusterServiceDelete(w http.ResponseWriter, r *http.Request, namespace string) {
	var request VClusterServiceDeleteRequestObject

	request.Namespace = namespace

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.VClusterServiceDelete(ctx, request.(VClusterServiceDeleteRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "VClusterServiceDelete")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(VClusterServiceDeleteResponseObject); ok {
		if err := validResponse.VisitVClusterServiceDeleteResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// VClusterServiceGet operation middleware
func (sh *strictHandler) VClusterServiceGet(w http.ResponseWriter, r *http.Request, namespace string) {
	var request VClusterServiceGetRequestObject

	request.Namespace = namespace

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.VClusterServiceGet(ctx, request.(VClusterServiceGetRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "VClusterServiceGet")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(VClusterServiceGetResponseObject); ok {
		if err := validResponse.VisitVClusterServiceGetResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// VClusterServiceCreate operation middleware
func (sh *strictHandler) VClusterServiceCreate(w http.ResponseWriter, r *http.Request, namespace string) {
	var request VClusterServiceCreateRequestObject

	request.Namespace = namespace

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.VClusterServiceCreate(ctx, request.(VClusterServiceCreateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "VClusterServiceCreate")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(VClusterServiceCreateResponseObject); ok {
		if err := validResponse.VisitVClusterServiceCreateResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// VClusterServiceKubeconfig operation middleware
func (sh *strictHandler) VClusterServiceKubeconfig(w http.ResponseWriter, r *http.Request, namespace string, params VClusterServiceKubeconfigParams) {
	var request VClusterServiceKubeconfigRequestObject

	request.Namespace = namespace
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.VClusterServiceKubeconfig(ctx, request.(VClusterServiceKubeconfigRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "VClusterServiceKubeconfig")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(VClusterServiceKubeconfigResponseObject); ok {
		if err := validResponse.VisitVClusterServiceKubeconfigResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xZzXLbNhB+Fcy2R4aSXSe1eXMcx+NJmnqa/hxsHyBwZSGFAAZYKlY1evcOAEkkK1FK",
	"7KhuJzxpRAL7g/2+3cVyBsKMC6NRk4NsBgW3fIyENvz7yeSoXPqmHKAweijvfi5IGu1SgZbkUApOeFrS",
	"yFhJ01ecuN+UoxNWhoWQwUvu8MXRM9TC5Jiz2kaW+w0JSL/sY4l2CgloPkbIoFV+Ak6McBwUDY0dc4IM",
	"BlNCSICmhd/ryEp9B/N50m6/1A5FadGL2aR/9b6ubyF/YIxCrrcrKMqBkuLNsTvXeWGkpjZN6ws3qFy5",
	"NF++rIfn3FpjT5VFnk/P76VbRNKawp8iuhgU4lJtEOnP3xHXAje+JEmq5U14MAPU5Riya2gacLspHBY/",
	"ltJi7peHt0v5ydK+mjWVBDP4gIKgOu7g8AVqtFI8hatL1ft38p2h16bU+VN4udK9fzd/0zyy/C98Elcb",
	"+vfqrs8UViOhe8fH6AoebW86HFPDDMb8/i3qOxpB9uIogbHUy78Hu2wMIrbYMTlTpSO0X0d5AhO0LiT8",
	"6lD76cFJ+hwS6KeH/bT/bIDE05PdxxsMqCSuO+GToM/OkqbvfTKMdr9EbtH6auH/hSwZsnV4XFWHEVER",
	"E6nUQ7Ner06vLhlqPlBS37GpKRkZVlgzkd4Y5otlScgEL7iQNGVSM86qoDIRj/VG3+hfXp+xk6PnP4ZN",
	"nORAVajJ4Gwh6Upx8oWMvUc7kaLueQaTQ3+2pkDNCwkZ/JD20z4kUHAaBad7f65U+793SOsevZWOGFeq",
	"bqZegs8FH80nDUGP5X7TZQ4ZVKu9APAxcoXRLmo67Pf9jzCaMBY3XhTKF2xpdO+Di1CoCpkkHIeN31sc",
	"Qgbf9aq+o7coab0tHFmRFri1fBoj2PTz1xEyjyN0xEbcMVcKgZhjnvrdR19o8GfY2ShDLQY5tBO0TJhS",
	"5UwbYqXO0fo8kTOqGZyX6JEm9YQrmTM31cTvF4Yf7MXwRs7bYP2pEOgck46VtZWpXzpP6sDrzVZomkf0",
	"KSRcx+Gr8LxJl9XOVhiuIBC3B/BXLer1oqnyhKh6qpVUqGcWsiVu661uHwnxtfawQ+gTIdSbdLQXk1Y9",
	"0Y7D5Nqf5FA2zxBzZtGZ0gpMo4SNCfsCicWmwjE+MCU9mDMXSP9hwjy0FHTE6oi1i1iFcRuYdWaRt5ag",
	"dhrFbetMWjfTC2Nm6Jlpa0QlwwbIRBCTL0ceHQU7Cj6Mgid7Mak5wNkRYmH0UElBjn2SNAqHKUprURNz",
	"5DlmhuFhjMCOrjE8jvOz1luML4qRt3GhjxePh9QkW+rvXn9IpZhFKq1u7prysWJDqTDYfaMXIsgEaysh",
	"7cmgErbH0ppsDlulrrd7tPkYIetTycdIa53mfkb+Irynno9aE9TV7FdqHuapG0alX5ahulr7oFq7hdYT",
	"UQ2Zqlthk1e/LwZRi/HHN3DL63D2uMvSVvz87288q8Fsh6x//7awFVptt4AOXR26Hlcfv0b/u4zsntrf",
	"f3Cha4K7JrgjeY3ktW+SgQT1r5HXtz7EUeCmwdHp1SVbfvNLoLRq8Zky6/WUEVyNjKPsuH/c780Wy+aQ",
	"wIRbyQcqQqb2+TXHIS+VR8XkAJKtqpZfasPCySHczufz2/nfAQAA//8/jgCsEyQAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
