apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: devpod-demo
  labels:
    app: devpod-demo
spec:
  ports:
    - port: 3306
  selector:
    app: devpod-demo
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: devpod-demo
  labels:
    app: devpod-demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: devpod-demo
  labels:
    app: devpod-demo
spec:
  selector:
    matchLabels:
      app: devpod-demo
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: devpod-demo
        tier: mysql
    spec:
      containers:
        - image: mysql:8.0
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: password
            - name: MYSQL_DATABASE
              value: demo
            - name: MYSQL_USER
              value: admin
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: password
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
